### ISSUE TITLE
Please add arm64 architecture

### ISSUE THREAD

**Issue by rafrafek** [redis/redis-snap#7]
Please add arm64 architecture to https://snapcraft.io/redis

![screenshot](https://user-images.githubusercontent.com/23004737/146960620-24cd0cc5-7b40-433c-98a3-346f6d1814da.png)

**Comment by yossigo** [comment]
@rafrafek This is a good idea, will need to look into if/how snapcraft handles cross compilation, or come up with a different approach to integrate arm64 builds into the GitHub Actions CI we have at the moment.

**Comment by yossigo** [comment]
Resolved by #8.

Right now only the daily unstable build is available for arm64 for testing. Once Redis 7.0 is released, it will be supported on both arm64 and amd64.
